<nav class="navbar fixed-bottom navbar-light bg-light">
    <div class="navbar-nav mx-auto">
    <div class="nav-item">
        <?php echo "Copyright &copy; 1999-" . date('Y'). " Absolute Rentals Inc. <span id=\"demo\"></span>" ?>
    </div></div>
</nav>


<script
        src="https://code.jquery.com/jquery-3.2.1.js"
        integrity="sha256-DZAnKJ/6XZ9si04Hgrsxu/8s717jcIzLy3oi35EouyE="
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/js/bootstrap.min.js"
        integrity="sha384-a5N7Y/aK3qNeh15eJKGWxsqtnX/wWdSZSKp+81YjTmS15nvnvxKHuzaWwXHDli+4"
        crossorigin="anonymous"></script>


<script src="/inc/js/events.js"></script>
<script src="/inc/js/event_segments.js"></script>
<script src="/inc/js/segment_details.js"></script>


</body>
</html>